# Generated by Django 4.2.11 on 2024-04-02 19:13

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    # Create a group for customers
    customers_group, created = Group.objects.get_or_create(name='Customers')
    # Create a group for staff
    staff_group, created = Group.objects.get_or_create(name='Staff')


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]