# Generated by Django 4.2.11 on 2024-04-03 15:52

from django.db import migrations
from django.contrib.auth.hashers import make_password
from register.models import Staff
from django.contrib.auth.models import User, Group


def create_initial_admin_user(apps, schema_editor):
    # Define the user details
    username = "admin1"
    first_name = "Admin"
    last_name = "User"
    email = "admin@example.com"
    password = "admin1"

    user_admin = User.objects.create(
        username=username,
        first_name=first_name,
        last_name=last_name,
        email=email,
        password=make_password(password)  # Ensures the password is hashed
    )

    # Fetch or create the "Staff" group
    staff_group = Group.objects.get(name='Staff')

    # Add the user to the "Staff" group
    staff_group.user_set.add(user_admin)

    # Create a Staff object for the user
    Staff.objects.create(user_admin=user_admin)



class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.RunPython(create_initial_admin_user),
    ]
