# Generated by Django 4.2.11 on 2024-03-25 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0005_auto_20240325_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Customer',
        ),
    ]
