# Generated by Django 4.2.11 on 2024-03-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_account_customer'),
    ]

    operations = [
    ]
